services:
  db:
    image: postgres-fastapi-base-project:1.0
    build:
      context: postgres_image/
    container_name: postgres-fastapi-base-cnt
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER} $${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata-fastapi-base:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - base-fastapi-app-network
  backend:
    image: backend-fastapi-base-app:1.0
    build:
      context: backend/
    container_name: backend-fastapi-base-cnt
    volumes:
      - ./logs/:/app/logs/
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - base-fastapi-app-network
  nginx:
    image: nginx-fastapi-base-app:1.0
    build:
      context: nginx/
    container_name: nginx-fastapi-base-cnt
    volumes:
      - ./static:/var/www/static
    depends_on:
      - db
      - backend
    ports:
      - "80:80"
    networks:
      - base-fastapi-app-network

networks:
  base-fastapi-app-network:

volumes:
  pgdata-fastapi-base:
