"""fix: change fingerprint type from str to int

Revision ID: 0a4fb26b3c74
Revises: 5ff22cfba6c5
Create Date: 2025-08-26 15:58:43.525810

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a4fb26b3c74"
down_revision: str | Sequence[str] | None = "5ff22cfba6c5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("""
        ALTER TABLE refresh_token ALTER COLUMN fingerprint TYPE INTEGER using
         fingerprint::integer
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refresh_token",
        "fingerprint",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
    op.execute(
        """ALTER TABLE refresh_token ALTER COLUMN fingerprint TYPE VARCHAR(255)
         using fingerprint::varchar"""
    )
