"""fix: add composite pk in the status_translate instead single

Revision ID: 10bdf9662be6
Revises: 27642e39f3d6
Create Date: 2025-07-17 08:46:03.561307

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10bdf9662be6"
down_revision: str | Sequence[str] | None = "27642e39f3d6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute(
        "alter table status_translate drop constraint status_translate_pkey"
    )
    op.execute(
        "alter table status_translate add primary key (language_id, status_id)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute(
        "alter table status_translate drop constraint status_translate_pkey"
    )
    op.execute("alter table status_translate add primary key (status_id)")
