"""fix: return the cfgname column in language table

Revision ID: 144350456758
Revises: c629fb25b3b0
Create Date: 2025-07-20 21:03:34.601294

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "144350456758"
down_revision: str | Sequence[str] | None = "c629fb25b3b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "language", sa.Column("cfgname", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("language", "cfgname")
    # ### end Alembic commands ###
