"""fix: add email value to UserDeleted table

Revision ID: 17e9216ae629
Revises: 0d30d0aacd26
Create Date: 2025-09-01 16:19:32.232470

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17e9216ae629"
down_revision: str | Sequence[str] | None = "0d30d0aacd26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_deleted",
        sa.Column("email", sa.String(length=400), nullable=False),
    )
    # ### end Alembic commands ###
    op.execute("""
        CREATE OR REPLACE FUNCTION move_to_user_deleted()
        RETURNS TRIGGER AS $$
        BEGIN
            INSERT INTO user_deleted (user_id, login, email, password, role_id, is_registered, deleted_at)
            VALUES (OLD.user_id, OLD.login, OLD.email, OLD.password, OLD.role_id, OLD.is_registered, NOW())
            ON CONFLICT (user_id) DO UPDATE SET email = EXCLUDED.email, login = EXCLUDED.login, password = EXCLUDED.password, role_id = EXCLUDED.role_id, is_registered = EXCLUDED.is_registered, deleted_at = NOW();
            RETURN OLD;
        END;
        $$ LANGUAGE plpgsql;""")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_deleted", "email")
    # ### end Alembic commands ###
