"""fix: move unique constraint from md_title to (md_title, language_id)

Revision ID: 18a9ae60dfff
Revises: fee587860c1e
Create Date: 2025-07-27 13:48:53.422342

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18a9ae60dfff"
down_revision: str | Sequence[str] | None = "fee587860c1e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "unique_md_title_language", "content", ["md_title", "language_id"]
    )
    op.create_unique_constraint(
        "unique_md_title_language_deleted",
        "content_deleted",
        ["md_title", "language_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "unique_md_title_language", "content_deleted", type_="unique"
    )
    op.drop_constraint("unique_md_title_language", "content", type_="unique")
    # ### end Alembic commands ###
