"""fix: change fingerprint type from int32 to int64

Revision ID: 1d3d4149c3d2
Revises: 17e9216ae629
Create Date: 2025-09-01 16:27:07.421451

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1d3d4149c3d2'
down_revision: str | Sequence[str] | None = '17e9216ae629'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
