"""feat: move image_src to article_translate, so allowed multi-language supporting for article images.

Revision ID: 1eb12a35658c
Revises: 23c392fbd236
Create Date: 2025-07-16 22:00:08.811610

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1eb12a35658c'
down_revision: str | Sequence[str] | None = '23c392fbd236'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'image_src')
    op.add_column('article_translate', sa.Column('image_src', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_translate', 'image_src')
    op.add_column('article', sa.Column('image_src', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
