"""fix: remove slug from tag table

Revision ID: 23c392fbd236
Revises: c411102c97de
Create Date: 2025-07-16 21:48:46.032871

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '23c392fbd236'
down_revision: str | Sequence[str] | None = 'c411102c97de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tag_slug_key'), 'tag', type_='unique')
    op.drop_column('tag', 'slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('tag_slug_key'), 'tag', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
