"""feat: drop unique constraint from translated_fields

Revision ID: 281e949f22cb
Revises: 799f116f48eb
Create Date: 2025-07-04 14:48:57.501606

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "281e949f22cb"
down_revision: str | Sequence[str] | None = "799f116f48eb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("aroma_translate_name_key"), "aroma_translate", type_="unique"
    )
    op.drop_constraint(
        op.f("grape_translate_name_key"), "grape_translate", type_="unique"
    )
    op.drop_constraint(
        op.f("product_translate_name_key"), "product_translate", type_="unique"
    )
    op.drop_constraint(
        op.f("wine_category_translate_name_key"),
        "wine_category_translate",
        type_="unique",
    )
    op.drop_constraint(
        op.f("wine_type_translate_name_key"),
        "wine_type_translate",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("wine_type_translate_name_key"),
        "wine_type_translate",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("wine_category_translate_name_key"),
        "wine_category_translate",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("product_translate_name_key"),
        "product_translate",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("grape_translate_name_key"),
        "grape_translate",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("aroma_translate_name_key"),
        "aroma_translate",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
