"""feat: add statuses for article

Revision ID: 2b01a985180a
Revises: 5652e7c03723
Create Date: 2025-07-16 18:54:28.048029

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b01a985180a"
down_revision: str | Sequence[str] | None = "5652e7c03723"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article", sa.Column("status_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        None,
        "article",
        "status",
        ["status_id"],
        ["status_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "article", type_="foreignkey")
    op.drop_column("article", "status_id")
    # ### end Alembic commands ###
