"""feat: add cascade delete on all tables

Revision ID: 4040387543fe
Revises: 8b840e7f6b66
Create Date: 2025-07-07 17:18:30.129287

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4040387543fe'
down_revision: str | Sequence[str] | None = '8b840e7f6b66'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('aroma_translate_language_id_fkey'), 'aroma_translate', type_='foreignkey')
    op.drop_constraint(op.f('aroma_translate_aroma_id_fkey'), 'aroma_translate', type_='foreignkey')
    op.create_foreign_key(None, 'aroma_translate', 'aroma', ['aroma_id'], ['aroma_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'aroma_translate', 'language', ['language_id'], ['language_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('aroma_wine_product_id_fkey'), 'aroma_wine', type_='foreignkey')
    op.drop_constraint(op.f('aroma_wine_aroma_id_fkey'), 'aroma_wine', type_='foreignkey')
    op.create_foreign_key(None, 'aroma_wine', 'wine', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'aroma_wine', 'aroma', ['aroma_id'], ['aroma_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('black_refresh_token_list_refresh_token_id_fkey'), 'black_refresh_token_list', type_='foreignkey')
    op.create_foreign_key(None, 'black_refresh_token_list', 'refresh_token', ['refresh_token_id'], ['refresh_token_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('country_flag_id_fkey'), 'country', type_='foreignkey')
    op.create_foreign_key(None, 'country', 'flag', ['flag_id'], ['flag_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('country_translate_country_id_fkey'), 'country_translate', type_='foreignkey')
    op.drop_constraint(op.f('country_translate_language_id_fkey'), 'country_translate', type_='foreignkey')
    op.create_foreign_key(None, 'country_translate', 'country', ['country_id'], ['country_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'country_translate', 'language', ['language_id'], ['language_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('grape_region_id_fkey'), 'grape', type_='foreignkey')
    op.create_foreign_key(None, 'grape', 'region', ['region_id'], ['region_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('grape_translate_grape_id_fkey'), 'grape_translate', type_='foreignkey')
    op.drop_constraint(op.f('grape_translate_language_id_fkey'), 'grape_translate', type_='foreignkey')
    op.create_foreign_key(None, 'grape_translate', 'grape', ['grape_id'], ['grape_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grape_translate', 'language', ['language_id'], ['language_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('language_flag_id_fkey'), 'language', type_='foreignkey')
    op.create_foreign_key(None, 'language', 'flag', ['flag_id'], ['flag_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_presentation_type_id_fkey'), 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'presentation_type', ['presentation_type_id'], ['presentation_type_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('product_translate_language_id_fkey'), 'product_translate', type_='foreignkey')
    op.drop_constraint(op.f('product_translate_product_id_fkey'), 'product_translate', type_='foreignkey')
    op.create_foreign_key(None, 'product_translate', 'product', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'product_translate', 'language', ['language_id'], ['language_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('refresh_token_user_id_fkey'), 'refresh_token', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_token', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('region_translate_language_id_fkey'), 'region_translate', type_='foreignkey')
    op.drop_constraint(op.f('region_translate_region_id_fkey'), 'region_translate', type_='foreignkey')
    op.create_foreign_key(None, 'region_translate', 'language', ['language_id'], ['language_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'region_translate', 'region', ['region_id'], ['region_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('sort_product_id_fkey'), 'sort', type_='foreignkey')
    op.drop_constraint(op.f('sort_grape_id_fkey'), 'sort', type_='foreignkey')
    op.create_foreign_key(None, 'sort', 'wine', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sort', 'grape', ['grape_id'], ['grape_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_role_id_fkey'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['role_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('wine_wine_category_id_fkey'), 'wine', type_='foreignkey')
    op.drop_constraint(op.f('wine_wine_type_id_fkey'), 'wine', type_='foreignkey')
    op.drop_constraint(op.f('wine_product_id_fkey'), 'wine', type_='foreignkey')
    op.create_foreign_key(None, 'wine', 'wine_category', ['wine_category_id'], ['wine_category_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wine', 'wine_type', ['wine_type_id'], ['wine_type_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wine', 'product', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('wine_category_translate_wine_category_id_fkey'), 'wine_category_translate', type_='foreignkey')
    op.drop_constraint(op.f('wine_category_translate_language_id_fkey'), 'wine_category_translate', type_='foreignkey')
    op.create_foreign_key(None, 'wine_category_translate', 'wine_category', ['wine_category_id'], ['wine_category_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wine_category_translate', 'language', ['language_id'], ['language_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('wine_translate_wine_id_fkey'), 'wine_translate', type_='foreignkey')
    op.drop_constraint(op.f('wine_translate_language_id_fkey'), 'wine_translate', type_='foreignkey')
    op.create_foreign_key(None, 'wine_translate', 'wine', ['wine_id'], ['product_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wine_translate', 'language', ['language_id'], ['language_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('wine_type_translate_language_id_fkey'), 'wine_type_translate', type_='foreignkey')
    op.drop_constraint(op.f('wine_type_translate_wine_type_id_fkey'), 'wine_type_translate', type_='foreignkey')
    op.create_foreign_key(None, 'wine_type_translate', 'language', ['language_id'], ['language_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wine_type_translate', 'wine_type', ['wine_type_id'], ['wine_type_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wine_type_translate', type_='foreignkey')
    op.drop_constraint(None, 'wine_type_translate', type_='foreignkey')
    op.create_foreign_key(op.f('wine_type_translate_wine_type_id_fkey'), 'wine_type_translate', 'wine_type', ['wine_type_id'], ['wine_type_id'])
    op.create_foreign_key(op.f('wine_type_translate_language_id_fkey'), 'wine_type_translate', 'language', ['language_id'], ['language_id'])
    op.drop_constraint(None, 'wine_translate', type_='foreignkey')
    op.drop_constraint(None, 'wine_translate', type_='foreignkey')
    op.create_foreign_key(op.f('wine_translate_language_id_fkey'), 'wine_translate', 'language', ['language_id'], ['language_id'])
    op.create_foreign_key(op.f('wine_translate_wine_id_fkey'), 'wine_translate', 'wine', ['wine_id'], ['product_id'])
    op.drop_constraint(None, 'wine_category_translate', type_='foreignkey')
    op.drop_constraint(None, 'wine_category_translate', type_='foreignkey')
    op.create_foreign_key(op.f('wine_category_translate_language_id_fkey'), 'wine_category_translate', 'language', ['language_id'], ['language_id'])
    op.create_foreign_key(op.f('wine_category_translate_wine_category_id_fkey'), 'wine_category_translate', 'wine_category', ['wine_category_id'], ['wine_category_id'])
    op.drop_constraint(None, 'wine', type_='foreignkey')
    op.drop_constraint(None, 'wine', type_='foreignkey')
    op.drop_constraint(None, 'wine', type_='foreignkey')
    op.create_foreign_key(op.f('wine_product_id_fkey'), 'wine', 'product', ['product_id'], ['product_id'])
    op.create_foreign_key(op.f('wine_wine_type_id_fkey'), 'wine', 'wine_type', ['wine_type_id'], ['wine_type_id'])
    op.create_foreign_key(op.f('wine_wine_category_id_fkey'), 'wine', 'wine_category', ['wine_category_id'], ['wine_category_id'])
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('user_role_id_fkey'), 'user', 'role', ['role_id'], ['role_id'])
    op.drop_constraint(None, 'sort', type_='foreignkey')
    op.drop_constraint(None, 'sort', type_='foreignkey')
    op.create_foreign_key(op.f('sort_grape_id_fkey'), 'sort', 'grape', ['grape_id'], ['grape_id'])
    op.create_foreign_key(op.f('sort_product_id_fkey'), 'sort', 'wine', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'region_translate', type_='foreignkey')
    op.drop_constraint(None, 'region_translate', type_='foreignkey')
    op.create_foreign_key(op.f('region_translate_region_id_fkey'), 'region_translate', 'region', ['region_id'], ['region_id'])
    op.create_foreign_key(op.f('region_translate_language_id_fkey'), 'region_translate', 'language', ['language_id'], ['language_id'])
    op.drop_constraint(None, 'refresh_token', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_token_user_id_fkey'), 'refresh_token', 'user', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'product_translate', type_='foreignkey')
    op.drop_constraint(None, 'product_translate', type_='foreignkey')
    op.create_foreign_key(op.f('product_translate_product_id_fkey'), 'product_translate', 'product', ['product_id'], ['product_id'])
    op.create_foreign_key(op.f('product_translate_language_id_fkey'), 'product_translate', 'language', ['language_id'], ['language_id'])
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key(op.f('product_presentation_type_id_fkey'), 'product', 'presentation_type', ['presentation_type_id'], ['presentation_type_id'])
    op.drop_constraint(None, 'language', type_='foreignkey')
    op.create_foreign_key(op.f('language_flag_id_fkey'), 'language', 'flag', ['flag_id'], ['flag_id'])
    op.drop_constraint(None, 'grape_translate', type_='foreignkey')
    op.drop_constraint(None, 'grape_translate', type_='foreignkey')
    op.create_foreign_key(op.f('grape_translate_language_id_fkey'), 'grape_translate', 'language', ['language_id'], ['language_id'])
    op.create_foreign_key(op.f('grape_translate_grape_id_fkey'), 'grape_translate', 'grape', ['grape_id'], ['grape_id'])
    op.drop_constraint(None, 'grape', type_='foreignkey')
    op.create_foreign_key(op.f('grape_region_id_fkey'), 'grape', 'region', ['region_id'], ['region_id'])
    op.drop_constraint(None, 'country_translate', type_='foreignkey')
    op.drop_constraint(None, 'country_translate', type_='foreignkey')
    op.create_foreign_key(op.f('country_translate_language_id_fkey'), 'country_translate', 'language', ['language_id'], ['language_id'])
    op.create_foreign_key(op.f('country_translate_country_id_fkey'), 'country_translate', 'country', ['country_id'], ['country_id'])
    op.drop_constraint(None, 'country', type_='foreignkey')
    op.create_foreign_key(op.f('country_flag_id_fkey'), 'country', 'flag', ['flag_id'], ['flag_id'])
    op.drop_constraint(None, 'black_refresh_token_list', type_='foreignkey')
    op.create_foreign_key(op.f('black_refresh_token_list_refresh_token_id_fkey'), 'black_refresh_token_list', 'refresh_token', ['refresh_token_id'], ['refresh_token_id'])
    op.drop_constraint(None, 'aroma_wine', type_='foreignkey')
    op.drop_constraint(None, 'aroma_wine', type_='foreignkey')
    op.create_foreign_key(op.f('aroma_wine_aroma_id_fkey'), 'aroma_wine', 'aroma', ['aroma_id'], ['aroma_id'])
    op.create_foreign_key(op.f('aroma_wine_product_id_fkey'), 'aroma_wine', 'wine', ['product_id'], ['product_id'])
    op.drop_constraint(None, 'aroma_translate', type_='foreignkey')
    op.drop_constraint(None, 'aroma_translate', type_='foreignkey')
    op.create_foreign_key(op.f('aroma_translate_aroma_id_fkey'), 'aroma_translate', 'aroma', ['aroma_id'], ['aroma_id'])
    op.create_foreign_key(op.f('aroma_translate_language_id_fkey'), 'aroma_translate', 'language', ['language_id'], ['language_id'])
    # ### end Alembic commands ###
