"""feat: add tsv_content trigger, function and index for article

Revision ID: 47ce52168a92
Revises: 6a452d282ffb
Create Date: 2025-07-18 18:02:59.607608

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47ce52168a92"
down_revision: str | Sequence[str] | None = "6a452d282ffb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("""alter table language add column cfgname regconfig unique;""")
    op.execute("""
        create or replace function update_tsvector() returns trigger as $$
        declare
	language varchar = (select cfgname from language where language_id = NEW.language_id);
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = language) THEN
                NEW.tsv_content := setweight(
			to_tsvector(language::regconfig, NEW.title), 'a'
		) || setweight(
			to_tsvector(language::regconfig, NEW.content), 'b'
		);
            ELSE
                NEW.tsv_content := to_tsvector('simple'::regconfig, NEW.content);
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        create or replace TRIGGER tsvector_update
        BEFORE INSERT OR UPDATE
        ON article_translate
        FOR EACH ROW
        EXECUTE FUNCTION update_tsvector();
        """)
    op.execute("""
    CREATE INDEX article_translate_idx ON article_translate USING GIN(tsv_content);
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute("DROP TRIGGER tsvector_update ON article_translate;")
    op.execute("DROP FUNCTION update_tsvector();")
    op.execute("DROP INDEX article_translate_idx;")
    op.execute("""alter table language drop column cfgname;""")
