"""fix: remove len constraint of slug from tag in relation with no existing it

Revision ID: 4c05946b7820
Revises: 1eb12a35658c
Create Date: 2025-07-16 22:27:33.349677

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c05946b7820"
down_revision: str | Sequence[str] | None = "1eb12a35658c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute("alter table tag drop constraint if exists tag_slug_check;")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
