"""feat: add status data

Revision ID: 5652e7c03723
Revises: cb6f109a04e5
Create Date: 2025-07-16 18:50:35.195419

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5652e7c03723'
down_revision: str | Sequence[str] | None = 'cb6f109a04e5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('status_translate',
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('language_id', sa.VARCHAR(length=10), nullable=False),
    sa.CheckConstraint('length(name) > 0', name='check_name_len'),
    sa.ForeignKeyConstraint(['language_id'], ['language.language_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['status.status_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('status_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_translate')
    op.drop_table('status')
    # ### end Alembic commands ###
