"""fix: lead_id in the deal table now unique

Revision ID: 668a7da7e661
Revises: a90cb03beecc
Create Date: 2025-08-01 15:05:01.506499

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '668a7da7e661'
down_revision: str | Sequence[str] | None = 'a90cb03beecc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'deal', ['lead_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deal', type_='unique')
    # ### end Alembic commands ###
