"""feat: add unique constraint (language_id, name) to CountryTranslate

Revision ID: 799f116f48eb
Revises: 9901fc81008c
Create Date: 2025-07-03 18:55:53.122802

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '799f116f48eb'
down_revision: str | Sequence[str] | None = '9901fc81008c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'country_translate', ['language_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country_translate', type_='unique')
    # ### end Alembic commands ###
