"""fix: drop unique constaint from RegionTranslate.name

Revision ID: 8a22b92e848e
Revises: f8c82835ed96
Create Date: 2025-07-03 15:35:50.806230

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a22b92e848e"
down_revision: str | Sequence[str] | None = "f8c82835ed96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("region_translate_name_key"), "region_translate", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("region_translate_name_key"),
        "region_translate",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
