"""fix: change type of deal_cost from money to numeric for right ORM works

Revision ID: 90c8003bcc93
Revises: a73641e4e129
Create Date: 2025-07-31 19:05:33.157727

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90c8003bcc93'
down_revision: str | Sequence[str] | None = 'a73641e4e129'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal', 'cost',
               existing_type=postgresql.MONEY(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deal', 'cost',
               existing_type=sa.NUMERIC(),
               type_=postgresql.MONEY(),
               existing_nullable=False)
    # ### end Alembic commands ###
