"""fix: rewrite unique constraint for alembic to see it

Revision ID: 9901fc81008c
Revises: 8a22b92e848e
Create Date: 2025-07-03 17:16:50.970716

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9901fc81008c'
down_revision: str | Sequence[str] | None = '8a22b92e848e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'region_translate', ['language_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'region_translate', type_='unique')
    # ### end Alembic commands ###
