"""feat: reformat the update_tsvector trigger to delete all not-alpha characters

Revision ID: 9a1cd467a028
Revises: 144350456758
Create Date: 2025-07-20 21:13:18.526309

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9a1cd467a028"
down_revision: str | Sequence[str] | None = "144350456758"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute("""
        CREATE OR REPLACE FUNCTION update_tsvector()
        RETURNS TRIGGER AS $$
        DECLARE
            language VARCHAR = (
                SELECT cfgname
                FROM language
                WHERE language_id = NEW.language_id
            );
            to_tsv_title varchar = regexp_replace(NEW.title, '[^[:alpha:] ]', '', 'g');
            to_tsv_content text = regexp_replace(regexp_replace(NEW.content, '<br />', '', 'g'), '[^[:alpha:] ]', '', 'g');
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = language) THEN
                NEW.tsv_content :=
                    setweight(to_tsvector(language::regconfig, to_tsv_title), 'A') ||
                    setweight(to_tsvector(language::regconfig, to_tsv_content), 'B');
            ELSE
            NEW.tsv_content :=
                setweight(to_tsvector('simple'::regconfig, to_tsv_title), 'A') ||
                setweight(to_tsvector('simple'::regconfig, to_tsv_content), 'B');
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute("""
        CREATE OR REPLACE FUNCTION update_tsvector()
        RETURNS TRIGGER AS $$
        DECLARE
            language VARCHAR = (
                SELECT cfgname
                FROM language
                WHERE language_id = NEW.language_id
            );
        BEGIN
            -- Очистка title и content от всех символов кроме буквенных
            NEW.title := regexp_replace(NEW.title, '[^[:alpha:] ]', '', 'g');
            NEW.content := regexp_replace(NEW.content, '[^[:alpha:] ]', '', 'g');

            IF EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = language) THEN
                NEW.tsv_content :=
                    setweight(to_tsvector(language::regconfig, NEW.title), 'A') ||
                    setweight(to_tsvector(language::regconfig, NEW.content), 'B');
            ELSE
                NEW.tsv_content := to_tsvector('simple'::regconfig, NEW.content);
            END IF;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;""")
