"""feat: add cascade region delete

Revision ID: a52cafaf7ad2
Revises: a1bb00029f96
Create Date: 2025-06-29 14:53:53.428541

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a52cafaf7ad2"
down_revision: str | Sequence[str] | None = "a1bb00029f96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("region_country_id_fkey"), "region", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "region",
        "country",
        ["country_id"],
        ["country_id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "region", type_="foreignkey")
    op.create_foreign_key(
        op.f("region_country_id_fkey"),
        "region",
        "country",
        ["country_id"],
        ["country_id"],
    )
    # ### end Alembic commands ###
