"""fix: rename deal_value to cost in the deal table

Revision ID: a73641e4e129
Revises: efb51b17def0
Create Date: 2025-07-31 18:56:32.421106

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a73641e4e129'
down_revision: str | Sequence[str] | None = 'efb51b17def0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('cost', postgresql.MONEY(), nullable=False))
    op.add_column('deal', sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('deal', 'deal_fields')
    op.drop_column('deal', 'deal_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('deal_value', postgresql.MONEY(), autoincrement=False, nullable=False))
    op.add_column('deal', sa.Column('deal_fields', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('deal', 'fields')
    op.drop_column('deal', 'cost')
    # ### end Alembic commands ###
