"""fix: add lost_reason_addition_text

Revision ID: a8029ca82286
Revises: 668a7da7e661
Create Date: 2025-08-01 15:51:27.963965

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a8029ca82286'
down_revision: str | Sequence[str] | None = '668a7da7e661'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal', sa.Column('lost_reason_additional_text', sa.Text(), nullable=True))
    op.add_column('deal_history', sa.Column('lost_reason_additional_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal_history', 'lost_reason_additional_text')
    op.drop_column('deal', 'lost_reason_additional_text')
    # ### end Alembic commands ###
