"""fix: remove Lead table. Deal references now to user table

Revision ID: a90cb03beecc
Revises: 90c8003bcc93
Create Date: 2025-08-01 14:32:02.271678

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a90cb03beecc'
down_revision: str | Sequence[str] | None = '90c8003bcc93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deal_lead_id_fkey'), 'deal', type_='foreignkey')
    op.drop_table('lead')
    op.create_foreign_key(None, 'deal', 'user', ['lead_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deal', type_='foreignkey')
    op.create_foreign_key(op.f('deal_lead_id_fkey'), 'deal', 'lead', ['lead_id'], ['lead_id'], ondelete='CASCADE')
    op.create_table('lead',
    sa.Column('lead_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['user.user_id'], name=op.f('lead_lead_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.source_id'], name=op.f('lead_source_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id', name=op.f('lead_pkey'))
    )
    # ### end Alembic commands ###
