"""feat: initialize partner model

Revision ID: bdb7594c210f
Revises: 1d3d4149c3d2
Create Date: 2025-09-03 16:10:48.553953

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bdb7594c210f'
down_revision: str | Sequence[str] | None = '1d3d4149c3d2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_src', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('partner_id'),
    comment='Table for storing partner information'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner')
    # ### end Alembic commands ###
