"""fix: reformat article triggers

Revision ID: c1b8e7967252
Revises: 4c05946b7820
Create Date: 2025-07-16 23:14:13.353255

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c1b8e7967252"
down_revision: str | Sequence[str] | None = "4c05946b7820"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute("""
    CREATE OR REPLACE FUNCTION move_to_article_deleted()
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO article_deleted (article_id, author_id, slug, views_count, deleted_at, created_at, updated_at)
        VALUES (OLD.article_id, OLD.author_id, OLD.slug, OLD.views_count, NOW(), OLD.created_at, OLD.updated_at);
        RETURN OLD;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trigger_move_to_article_deleted
    BEFORE DELETE ON article
    FOR EACH ROW EXECUTE FUNCTION move_to_article_deleted();
    """)
    # Article-translate
    op.execute("""
    CREATE OR REPLACE FUNCTION move_to_article_translate_deleted()
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO article_translate_deleted (article_id, image_src, language_id, title, content, tsv_content, deleted_at)
        VALUES (OLD.article_id, OLD.image_src, OLD.language_id, OLD.title, OLD.content, OLD.tsv_content, NOW());
        RETURN OLD;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE OR REPLACE TRIGGER trigger_move_to_article_translate_deleted
    BEFORE DELETE ON article_translate
    FOR EACH ROW EXECUTE FUNCTION move_to_article_translate_deleted();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute("""
    CREATE OR REPLACE FUNCTION move_to_article_deleted()
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO article_deleted (image_src, article_id, author_id, slug, views_count, deleted_at, created_at, updated_at)
        VALUES (OLD.image_src, OLD.article_id, OLD.author_id, OLD.slug, OLD.views_count, NOW(), OLD.created_at, OLD.updated_at);
        RETURN OLD;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE OR REPLACE TRIGGER trigger_move_to_article_deleted
    BEFORE DELETE ON article
    FOR EACH ROW EXECUTE FUNCTION move_to_article_deleted();
    """)
    # Article-translate
    op.execute("""
    CREATE OR REPLACE FUNCTION move_to_article_translate_deleted()
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO article_translate_deleted (article_id, language_id, title, content, tsv_content, deleted_at)
        VALUES (OLD.article_id, OLD.language_id, OLD.title, OLD.content, OLD.tsv_content, NOW());
        RETURN OLD;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trigger_move_to_article_translate_deleted
    BEFORE DELETE ON article_translate
    FOR EACH ROW EXECUTE FUNCTION move_to_article_translate_deleted();
    """)
