"""feat: add blog_category_id in the article

Revision ID: c411102c97de
Revises: 7ef0f00a3eaf
Create Date: 2025-07-16 21:28:10.525093

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c411102c97de'
down_revision: str | Sequence[str] | None = '7ef0f00a3eaf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'blog_category', ['category_id'], ['blog_category_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'category_id')
    # ### end Alembic commands ###
