"""fix: add image_src to article_translate_deleted table

Revision ID: c5be6057a086
Revises: c1b8e7967252
Create Date: 2025-07-16 23:17:03.095373

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5be6057a086'
down_revision: str | Sequence[str] | None = 'c1b8e7967252'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_deleted', 'image_src')
    op.add_column('article_translate_deleted', sa.Column('image_src', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_translate_deleted', 'image_src')
    op.add_column('article_deleted', sa.Column('image_src', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
