"""fix: rename fk category_id to blog_category_id in the article

Revision ID: c629fb25b3b0
Revises: 47ce52168a92
Create Date: 2025-07-20 18:05:44.175168

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c629fb25b3b0"
down_revision: str | Sequence[str] | None = "47ce52168a92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "article", sa.Column("blog_category_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        op.f("article_category_id_fkey"), "article", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "article",
        "blog_category",
        ["blog_category_id"],
        ["blog_category_id"],
        ondelete="CASCADE",
    )
    op.drop_column("article", "category_id")
    op.drop_index(
        op.f("article_translate_idx"),
        table_name="article_translate",
        postgresql_using="gin",
    )
    op.drop_column("language", "cfgname")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "language",
        sa.Column(
            "cfgname",
            sa.NullType(),
            autoincrement=False,
            nullable=True,
            comment="Language name for tsv_content configuration.",
        ),
    )
    op.create_index(
        op.f("article_translate_idx"),
        "article_translate",
        ["tsv_content"],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column(
        "article",
        sa.Column(
            "category_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "article", type_="foreignkey")
    op.create_foreign_key(
        op.f("article_category_id_fkey"),
        "article",
        "blog_category",
        ["category_id"],
        ["blog_category_id"],
        ondelete="CASCADE",
    )
    op.drop_column("article", "blog_category_id")
    # ### end Alembic commands ###
