"""feat: add foreign-relation to the tables: wine - wine-category and wine - wine-type

Revision ID: f4e4a6b9c8d4
Revises: a52cafaf7ad2
Create Date: 2025-06-30 19:29:29.572275

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f4e4a6b9c8d4'
down_revision: str | Sequence[str] | None = 'a52cafaf7ad2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wine', sa.Column('wine_type_id', sa.Integer(), nullable=False))
    op.add_column('wine', sa.Column('wine_category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wine', 'wine_category', ['wine_category_id'], ['wine_category_id'])
    op.create_foreign_key(None, 'wine', 'wine_type', ['wine_type_id'], ['wine_type_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wine', type_='foreignkey')
    op.drop_constraint(None, 'wine', type_='foreignkey')
    op.drop_column('wine', 'wine_category_id')
    op.drop_column('wine', 'wine_type_id')
    # ### end Alembic commands ###
