"""fix: change fingerprint type to in64

Revision ID: f8621ef68817
Revises: 0a4fb26b3c74
Create Date: 2025-09-01 16:05:22.868875

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8621ef68817"
down_revision: str | Sequence[str] | None = "0a4fb26b3c74"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("content_md_title_key"), "content", type_="unique")
    # ### end Alembic commands ###
    op.execute("""
        ALTER TABLE refresh_token ALTER COLUMN fingerprint TYPE BIGINT using
         fingerprint::bigint
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("content_md_title_key"),
        "content",
        ["md_title"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
    op.execute("""
        ALTER TABLE refresh_token ALTER COLUMN fingerprint TYPE INTEGER using
         fingerprint::int
        """)
