"""fix: drop unique constraint from name in CountryTranslate

Revision ID: f8c82835ed96
Revises: f4e4a6b9c8d4
Create Date: 2025-07-02 17:58:36.129151

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f8c82835ed96"
down_revision: str | Sequence[str] | None = "f4e4a6b9c8d4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("country_translate_name_key"), "country_translate", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("country_translate_name_key"),
        "country_translate",
        ["name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
