"""feat: add triggers for soft article delete

Revision ID: fde0616937c2
Revises: d23d2c2e94a7
Create Date: 2025-07-16 17:39:52.179242

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fde0616937c2"
down_revision: str | Sequence[str] | None = "d23d2c2e94a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    # Article
    op.execute("""
    CREATE OR REPLACE FUNCTION move_to_article_deleted()
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO article_deleted (article_id, author_id, slug, views_count, image_src, deleted_at, created_at, updated_at)
        VALUES (OLD.article_id, OLD.author_id, OLD.slug, OLD.views_count, OLD.image_src, NOW(), OLD.created_at, OLD.updated_at);
        RETURN OLD;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trigger_move_to_article_deleted
    BEFORE DELETE ON article
    FOR EACH ROW EXECUTE FUNCTION move_to_article_deleted();
    """)
    # Article-translate
    op.execute("""
    CREATE OR REPLACE FUNCTION move_to_article_translate_deleted()
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO article_translate_deleted (article_id, language_id, title, content, tsv_content, deleted_at)
        VALUES (OLD.article_id, OLD.language_id, OLD.title, OLD.content, OLD.tsv_content, NOW());
        RETURN OLD;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trigger_move_to_article_translate_deleted
    BEFORE DELETE ON article_translate
    FOR EACH ROW EXECUTE FUNCTION move_to_article_translate_deleted();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    op.execute("drop trigger if exists trigger_move_to_article_deleted")
    op.execute(
        "drop trigger if exists trigger_move_to_article_translate_deleted"
    )

    op.execute("drop function if exists move_to_article_translate_deleted")
    op.execute("drop function if exists move_to_article_deleted")
