"""fix: remove not-null to content tables

Revision ID: fee587860c1e
Revises: 1a9d62fd2684
Create Date: 2025-07-27 13:25:57.819992

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fee587860c1e'
down_revision: str | Sequence[str] | None = '1a9d62fd2684'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content', 'md_description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content_deleted', 'md_description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('content_deleted', 'md_description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('content', 'md_description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
